apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo-staging
commonLabels:
  variant: staging

resources:
  - ../base

images:
  - name: cartservice
    newName: registry.digitalocean.com/microservices-demo-evg/cartservice
    newTag: v1.0.0
  - name: checkoutservice
    newName: registry.digitalocean.com/microservices-demo-evg/checkoutservice
    newTag: v1.0.0
  - name: currencyservice
    newName: registry.digitalocean.com/microservices-demo-evg/currencyservice
    newTag: v1.0.0
  - name: emailservice
    newName: registry.digitalocean.com/microservices-demo-evg/emailservice
    newTag: v1.0.0
  - name: frontend
    newName: registry.digitalocean.com/microservices-demo-evg/frontend
    newTag: v1.0.0
  - name: paymentservice
    newName: registry.digitalocean.com/microservices-demo-evg/paymentservice
    newTag: v1.0.0
  - name: productcatalogservice
    newName: registry.digitalocean.com/microservices-demo-evg/productcatalogservice
    newTag: v1.0.0
  - name: recommendationservice
    newName: registry.digitalocean.com/microservices-demo-evg/recommendationservice
    newTag: v1.0.0
  - name: shippingservice
    newName: registry.digitalocean.com/microservices-demo-evg/shippingservice
    newTag: v1.0.0
  
replicas:
  - name: cartservice
    count: 2
  - name: checkoutservice
    count: 2
  - name: currencyservice
    count: 2
  - name: emailservice
    count: 2
  - name: frontend
    count: 2
  - name: paymentservice
    count: 2
  - name: productcatalogservice
    count: 2
  - name: recommendationservice
    count: 2
  - name: shippingservice
    count: 2
